config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'home/index'
  root 'home#index'
  get 'home/rooms'
  get 'home/resorts'
  get 'home/about'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_footer.html.erb
<footer style="background-color:black;padding:0px 0px 0px 0px">
<p style="text-align:center;color:white">All rights reserved &copy LuxGroup</p>
</footer>

app/views/home/_header.html.erb
<nav class="navbar  navbar-expand-lg navbar-dark bg-dark" style="width:100%;">
  <div class="container-fluid">
    <%= link_to "LuxHotel" ,root_path, class:"navbar-brand"%>
    <%# <a class="navbar-brand" href="#">LuxHotel</a> %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">

        <li class="nav-item">
          <%= link_to "Rooms" ,home_rooms_path, class:"nav-link"%>
          <!-- <a class="nav-link" href="#">Rooms</a> -->
        </li>
        <li class="nav-item">
            <%= link_to "Resorts" ,home_resorts_path, class:"nav-link"%>
          <!-- <a class="nav-link" href="#">Resorts</a> -->
        </li>

        <li class="nav-item">
          <%= link_to "About" ,home_about_path, class:"nav-link"%>
          <!-- <a class="nav-link" href="#" >About</a> -->
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<div style="height:140vh;width:100vw;background-color:black;">

  <h2 style="text-align:center;color:white"><u>LuxGroup</u></h2><br/>
  <div style="height:60vh;width:50vw;background-color:transparent;margin-left:25vw;
              margin-right:25vw">
              <!-- image --><img  src="/assets/about.jpg" alt="bg1" style="min-width: 100%;
              max-height: 100%;border-radius:25px">
    </div>
    <div style="height:60vh;width:70vw;background-color:transparent;margin-left:15vw;margin-right:15vw;color:white">
      <!-- content --><br/>

      <p style="padding-left:10px">Lorem ipsum dolor sit amet, consectetur adipiscing elit,
        sed do eiusmod tempor incididunt ut labore et dolore magna
         aliqua. Ut enim ad minim veniam, quis nostrud exercitation
          ullamco laboris nisi ut aliquip ex ea commodo consequat.
          Duis aute irure dolor in reprehenderit in voluptate velit
           esse cillum dolore eu fugiat nulla pariatur. Excepteur sint
            occaecat cupidatat non proident, sunt in culpa qui officia
             deserunt mollit anim id est laborum</p>
             <p style="padding-left:10px">Lorem ipsum dolor sit amet, consectetur adipiscing elit,
               sed do eiusmod tempor incididunt ut labore et dolore magna
                aliqua. Ut enim ad minim veniam, quis nostrud exercitation
                 ullamco laboris nisi ut aliquip ex ea commodo consequat.
                 Duis aute irure dolor in reprehenderit in voluptate velit
                  esse cillum dolore eu fugiat nulla pariatur. Excepteur sint
                   occaecat cupidatat non proident, sunt in culpa qui officia
                    deserunt mollit anim id est laborum</p>
                    <p style="padding-left:10px">Lorem ipsum dolor sit amet, consectetur adipiscing elit,
                      sed do eiusmod tempor incididunt ut labore et dolore magna
                       aliqua. Ut enim ad minim veniam, quis nostrud exercitation
                        ullamco laboris nisi ut aliquip ex ea commodo consequat.
                        Duis aute irure dolor in reprehenderit in voluptate velit
                         esse cillum dolore eu fugiat nulla pariatur. Excepteur sint
                          occaecat cupidatat non proident, sunt in culpa qui officia
                           deserunt mollit anim id est laborum</p>
             <p style="padding-left:10px;float:left">Wishing you a happy stay</p>
            <p style="padding-right:10px;float:right">:- LuxGroup</p>
      </div>
</div>

app/views/home/index.html.erb
<section  style="height:100vh;width:100vw;padding:0px;margin:0px">
  <img  src="/assets/1.jpeg" alt="bg1" style="min-width: 100%;
  max-height: 100%;">
  <div  style="position: absolute;
      top: 100px;
      width:100%;text-align:center;color:white"><br/><br/>
<h1 >Your Search for Luxury ends here</h1><p>:-LuxGroup</p>
<div>
</section>

app/views/home/resorts.html.erb
<div>
<div style="height:110vh;width:100vw;background-color:black;">

  <h2 style="text-align:center;color:white"><u>Resorts</u></h2><br/>
  <div style="height:60vh;width:50vw;background-color:black;margin-left:25vw;
              margin-right:25vw">
              <!-- image --><img  src="/assets/hutResort.jpg" alt="bg1" style="min-width: 100%;
              max-height: 100%;border-radius:25px">
    </div>
    <div style="height:35vh;width:70vw;background-color:transparent;margin-left:15vw;margin-right:15vw;color:white">
      <!-- content --><br/>
      <h3 style="text-align:center"> &nbsp&nbsp<u>Hut Resort</u></h3>
      <p style="padding-left:10px">Lorem ipsum dolor sit amet, consectetur adipiscing elit,
        sed do eiusmod tempor incididunt ut labore et dolore magna
         aliqua. Ut enim ad minim veniam, quis nostrud exercitation
          ullamco laboris nisi ut aliquip ex ea commodo consequat.
          Duis aute irure dolor in reprehenderit in voluptate velit
           esse cillum dolore eu fugiat nulla pariatur. Excepteur sint
            occaecat cupidatat non proident, sunt in culpa qui officia
             deserunt mollit anim id est laborum</p>
             <p style="padding-left:10px;float:left">Maximum Accomodation :4</p>
            <p style="padding-right:10px;float:right">Price Starts at Rs.37999*</p>
      </div>
</div>
<hr style="margin:0px 0px 0px 0px;">
<div style="height:100vh;width:100vw;background-color:black">
  <br/>
  <div style="height:60vh;width:50vw;background-color:transparent;margin-left:25vw;
              margin-right:25vw;">
              <!-- image --><img  src="/assets/villaResort.jpg" alt="bg1" style="min-width: 100%;
              max-height: 100%;border-radius:25px">
    </div>
    <div style="height:35vh;width:70vw;background-color:transparent;margin-left:15vw;margin-right:15vw;color:white">
      <!-- content --><br/>
      <h3 style="text-align:center;"> &nbsp&nbsp<u>Villa Resort</u></h3>
      <p style="padding-left:10px">Lorem ipsum dolor sit amet, consectetur adipiscing elit,
        sed do eiusmod tempor incididunt ut labore et dolore magna
         aliqua. Ut enim ad minim veniam, quis nostrud exercitation
          ullamco laboris nisi ut aliquip ex ea commodo consequat.
          Duis aute irure dolor in reprehenderit in voluptate velit
           esse cillum dolore eu fugiat nulla pariatur. Excepteur sint
            occaecat cupidatat non proident, sunt in culpa qui officia
             deserunt mollit anim id est laborum</p>
             <p style="padding-left:10px;float:left">Maximum Accomodation :9</p>
            <p style="padding-right:10px;float:right">Price Starts at Rs.77999*</p>
      </div>
</div>
</div>

app/views/home/rooms.html.erb
<div style="width:100%;height:100%;background-color:black;">
  <br/>
<h1 style="text-align:center;color:white">🏠 <u>Rooms that fit your need</u> 🏠</h1>
<div style="height:50vh;width:100vw;">
  <div style="height:100%;width:70%;float:left;color:white"><br/>
    <!-- content --><h3 style="text-align:left;"> &nbsp&nbspHoneymoon suite :</h3>
                    <p style="padding-left:10px">Lorem ipsum dolor sit amet, consectetur adipiscing elit,
                      sed do eiusmod tempor incididunt ut labore et dolore magna
                       aliqua. Ut enim ad minim veniam, quis nostrud exercitation
                        ullamco laboris nisi ut aliquip ex ea commodo consequat.
                        Duis aute irure dolor in reprehenderit in voluptate velit
                         esse cillum dolore eu fugiat nulla pariatur. Excepteur sint
                          occaecat cupidatat non proident, sunt in culpa qui officia
                           deserunt mollit anim id est laborum</p><br/>
                           <p style="padding-left:10px;float:left">Maximum Accomodation :2</p>
                          <p style="padding-right:10px;float:right">Price Starts at Rs.7999*</p>
  </div>
  <div style="height:100%;width:30%;float:right;padding:1% 2% 1% 1%">
      <div style="width:100%;height:100%;">
        <!-- image will go here -->
        <img  src="/assets/honeymoon.jpg" alt="bg1" style="max-width: 100%;max-height: 100%;margin-top:20px">
      </div>
  </div>
</div>
<div style="height:50vh;width:100vw;">
  <div style="height:100%;width:30%;float:left;padding:1% 1% 1% 1%">
    <div style="width:100%;height:100%;">
      <!-- image will go here -->
      <img  src="/assets/luxury.jpg" alt="bg1" style="max-width: 100%;max-height: 100%;margin-top:8px">

    </div>
  </div>
  <div style="height:100%;width:70%;float:right;color:white">
    <!-- content --><br/>
    <h3 style="text-align:left;color:white">Luxury suite :</h3>
    <p style="padding-left:10px;padding-right:30px">Lorem ipsum dolor sit amet, consectetur adipiscing elit,
      sed do eiusmod tempor incididunt ut labore et dolore magna
       aliqua. Ut enim ad minim veniam, quis nostrud exercitation
        ullamco laboris nisi ut aliquip ex ea commodo consequat.
        Duis aute irure dolor in reprehenderit in voluptate velit
         esse cillum dolore eu fugiat nulla pariatur. Excepteur sint
          occaecat cupidatat non proident, sunt in culpa qui officia
           deserunt mollit anim id est laborum</p><br/>
           <p style="padding-left:10px;float:left">Maximum Accomodation :2</p>
          <p style="padding-right:30px;float:right">Price Starts at Rs.10999*</p>
  </div>
</div>

<div style="height:50vh;width:100vw;">
  <div style="height:100%;width:70%;float:left;color:white">
    <!-- content -->
    <br/>
    <h3 style="text-align:left;color:white"> &nbsp&nbspFamily suite :</h3>
    <p style="padding-left:10px">Lorem ipsum dolor sit amet, consectetur adipiscing elit,
      sed do eiusmod tempor incididunt ut labore et dolore magna
       aliqua. Ut enim ad minim veniam, quis nostrud exercitation
        ullamco laboris nisi ut aliquip ex ea commodo consequat.
        Duis aute irure dolor in reprehenderit in voluptate velit
         esse cillum dolore eu fugiat nulla pariatur. Excepteur sint
          occaecat cupidatat non proident, sunt in culpa qui officia
           deserunt mollit anim id est laborum</p><br/>
           <p style="padding-left:10px;float:left">Maximum Accomodation :4</p>
          <p style="padding-right:10px;float:right">Price Starts at Rs.12999*</p>
  </div>
  <div style="height:100%;width:30%;float:right;padding:1% 2% 1% 1%">
    <div style="width:100%;height:100%;">
      <!-- image will go here -->
      <img  src="/assets/twin.jpg" alt="bg1" style="max-width: 100%;max-height: 100%;margin-top:6%">

    </div>
  </div>
</div>

<div style="height:50vh;width:100vw;">
  <div style="height:100%;width:30%;float:left;padding:1% 1% 1% 1%">
    <div style="width:100%;height:100%;">
      <!-- image will go here -->
      <img  src="/assets/bunk.jpg" alt="bg1" style="max-width: 100%;max-height: 100%;">

    </div>
  </div>
  <div style="height:100%;width:70%;float:right;color:white">
    <!-- content --><br/>
    <h3 style="text-align:left;color:white">Group suite :</h3>
    <p style="padding-left:10px;padding-right:30px">Lorem ipsum dolor sit amet, consectetur adipiscing elit,
      sed do eiusmod tempor incididunt ut labore et dolore magna
       aliqua. Ut enim ad minim veniam, quis nostrud exercitation
        ullamco laboris nisi ut aliquip ex ea commodo consequat.
        Duis aute irure dolor in reprehenderit in voluptate velit
         esse cillum dolore eu fugiat nulla pariatur. Excepteur sint
          occaecat cupidatat non proident, sunt in culpa qui officia
           deserunt mollit anim id est laborum</p><br/>
           <p style="padding-left:10px;float:left">Maximum Accomodation :4</p>
          <p style="padding-right:30px;float:right">Price Starts at Rs.8999*</p>
  </div>
</div>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <title>LuxHotel</title>
  </head>
  <body>
    <div style="overflow-x:hidden;max-width:100vw">
    <%= render "home/header" %>
    <%= yield %>
    <%= render "home/footer" %>
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
    </div>
  </body>
</html>















<!DOCTYPE html>
<html>
  <head>


  </head>

  <body>

  </body>
</html>